import { NextResponse } from "next/server";
import { z } from "zod";
import { createSupabaseAdminClient } from "@/lib/supabase/server";

/**
 * Lightweight event tracker. Forwards anonymized usage events to Supabase
 * when configured; otherwise silently 204s so the client never errors.
 *
 * Recommended Supabase schema:
 *   create table public.events (
 *     id bigint generated by default as identity primary key,
 *     ts timestamptz default now(),
 *     event text not null,
 *     tool text,
 *     metadata jsonb
 *   );
 */
const schema = z.object({
  event: z.string().min(1).max(64),
  tool: z.string().min(1).max(64).optional(),
  metadata: z.record(z.unknown()).optional(),
});

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const parsed = schema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json({ error: "Invalid payload" }, { status: 400 });
    }
    const supabase = await createSupabaseAdminClient();
    if (!supabase) return new NextResponse(null, { status: 204 });
    await supabase.from("events").insert({
      event: parsed.data.event,
      tool: parsed.data.tool,
      metadata: parsed.data.metadata,
    });
    return NextResponse.json({ ok: true });
  } catch {
    return NextResponse.json({ error: "Server error" }, { status: 500 });
  }
}
